name: Feature testing
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Installing dependencies.
      run: npm i
    - name: Installing TS-Node
      run: npm install -D ts-node
    - name: Simple bot
      run: ts-node scripts/tests/simpleBot.ts
      env: 
        TOKEN: ${{ secrets.TEST_BOT_TOKEN }}
    - name: Message test
      run: ts-node scripts/tests/message.ts
      env:
        TOKEN: ${{ secrets.TEST_BOT_TOKEN }}